# Generated by Django 5.0.7 on 2024-07-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_qrcode_image_allergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials_ko',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrients_ko',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='product.product'),
        ),
    ]
