# Generated by Django 5.0.7 on 2024-07-19 15:14

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_caution_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.product_image_upload_to),
        ),
    ]
