# Generated by Django 5.0.7 on 2024-07-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_return', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlereturn',
            name='name',
            field=models.TextField(default='페트병 반환소'),
        ),
        migrations.AlterField(
            model_name='bottlereturn',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
