# Generated by Django 5.0.7 on 2024-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kiosk',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
