# Generated by Django 5.0.7 on 2024-07-19 18:28

import kiosk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_kiosk_name_alter_kiosk_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='image',
            field=models.ImageField(null=True, upload_to=kiosk.models.kiosk_image_upload_to),
        ),
    ]
